'use client';

import Link from 'next/link';
import { useState } from 'react';

const systems = [
  { id: '01', name: 'SENTIENT CORE', type: 'EDGE AI', status: 'DEPLOYED PROTOTYPE', copy: 'Local multimodal intelligence on NVIDIA Jetson. Inference, memory, voice, perception and service orchestration without making the cloud the brain.', tags: ['Jetson', 'LLM', 'Vision', 'MQTT'] },
  { id: '02', name: 'DRIFTER', type: 'MOBILE EDGE', status: 'HARDWARE INTEGRATED', copy: 'Raspberry Pi vehicle intelligence node combining OBD-II/CAN telemetry, deterministic rules, diagnostics and event logging.', tags: ['Raspberry Pi', 'CAN', 'OBD-II', 'Linux'] },
  { id: '03', name: 'MURMUR', type: 'PHYSICAL AI', status: 'ACTIVE R&D', copy: 'Wearable computing research exploring embedded sensing, haptics, optical systems and privacy-first product architecture.', tags: ['Embedded', 'Sensors', 'Haptics', 'Wearables'] },
  { id: '04', name: 'BENCHFORGE', type: 'AI + HARDWARE', status: 'PRIVATE ACTIVE BUILD', copy: 'A component-aware engineering workbench turning available parts into constrained concepts, pin plans, power checks and verification paths.', tags: ['AI Agents', 'Electronics', 'Validation', 'Firmware'] },
  { id: '05', name: 'MYCELIYUM', type: 'FIELD COMPUTING', status: 'APPLICATION PROTOTYPE', copy: 'Offline-first native Android field research software designed to remain useful when connectivity disappears.', tags: ['Kotlin', 'Compose', 'Offline', 'Maps'] },
  { id: '06', name: 'HEXPLAYER', type: 'PHYSICAL INTERFACE', status: 'BENCH PROTOTYPE', copy: 'NFC physical media interface: tap a tile, resolve an identity, hand off playback. Hardware becomes the interface.', tags: ['NFC', 'SPI', 'Raspberry Pi', 'UX'] },
];

const capabilities = [
  ['EDGE INTELLIGENCE', 'Local inference, model optimisation, perception pipelines and AI systems that continue operating at the edge.'],
  ['PHYSICAL COMPUTING', 'Microcontrollers, sensors, cameras, haptics, buses, power systems and custom hardware integration.'],
  ['SYSTEMS ENGINEERING', 'Linux services, networking, MQTT, APIs, databases, containers and deterministic system behaviour.'],
  ['AI ORCHESTRATION', 'Agents, tool routing, memory, multimodal workflows and cloud/edge division of labour.'],
];

export default function Home() {
  const [active, setActive] = useState(0);
  const system = systems[active];
  return (
    <main className="min-h-screen bg-[#050608] text-slate-100 selection:bg-cyan-300 selection:text-black">
      <nav className="sticky top-0 z-50 border-b border-white/10 bg-[#050608]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="font-mono text-sm font-bold tracking-[0.28em]">NULLVECTOR<span className="text-cyan-300">//</span>LABS</Link><div className="hidden gap-7 font-mono text-[10px] tracking-[0.18em] text-slate-400 md:flex"><a href="#systems">SYSTEMS</a><a href="#capabilities">CAPABILITIES</a><a href="#architecture">ARCHITECTURE</a><a href="#about">ABOUT</a></div><a href="mailto:justmyeverything@proton.me" className="border border-cyan-300/30 px-3 py-2 font-mono text-[9px] tracking-[0.16em] text-cyan-200 hover:border-cyan-200">CONTACT</a></div></nav>
      <section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.06)_1px,transparent_1px)] [background-size:48px_48px]" /><div className="absolute left-1/2 top-20 h-96 w-96 -translate-x-1/2 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative mx-auto grid min-h-[78vh] max-w-7xl items-center gap-12 px-5 py-24 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><div className="mb-7 flex items-center gap-3 font-mono text-[9px] tracking-[0.24em] text-cyan-300"><span className="h-2 w-2 animate-pulse rounded-full bg-cyan-300" /> INDEPENDENT APPLIED TECHNOLOGY LAB</div><h1 className="max-w-5xl text-6xl font-semibold leading-[.9] tracking-[-.06em] sm:text-7xl lg:text-9xl">INTELLIGENCE<br /><span className="text-slate-500">WITHOUT</span><br />BOUNDARIES.</h1><p className="mt-9 max-w-2xl text-lg leading-8 text-slate-400">NULLVECTOR LABS builds systems where artificial intelligence meets the physical world — edge compute, embedded hardware, perception, agents and interfaces engineered as one stack.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#systems" className="bg-cyan-300 px-5 py-3 font-mono text-[10px] font-bold tracking-[0.18em] text-black">EXPLORE THE SYSTEMS →</a><a href="#architecture" className="border border-white/15 px-5 py-3 font-mono text-[10px] tracking-[0.18em] text-slate-300">VIEW ARCHITECTURE</a></div></div><div className="relative mx-auto w-full max-w-lg"><div className="aspect-square rounded-full border border-cyan-300/20 p-8 shadow-[0_0_100px_rgba(34,211,238,.08)]"><div className="flex h-full items-center justify-center rounded-full border border-white/10 bg-black/30"><div className="relative h-44 w-44 rounded-full border border-cyan-300/50 bg-cyan-300/5 shadow-[0_0_70px_rgba(34,211,238,.18)]"><span className="absolute left-1/2 top-0 h-1/2 w-px origin-bottom -translate-x-1/2 rotate-45 bg-cyan-300/60" /><span className="absolute inset-8 rounded-full border border-dashed border-cyan-300/30" /><div className="absolute inset-0 flex items-center justify-center font-mono text-[10px] tracking-[.25em] text-cyan-200">NULL / VECTOR</div></div></div></div><div className="absolute -right-2 top-10 border border-white/10 bg-black/80 p-3 font-mono text-[8px] text-slate-500">EDGE NODE<br /><b className="text-emerald-300">● ONLINE</b></div><div className="absolute -bottom-2 -left-2 border border-white/10 bg-black/80 p-3 font-mono text-[8px] text-slate-500">LOCAL INFERENCE<br /><b className="text-cyan-200">READY</b></div></div></div></section>
      <section id="systems" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="mb-12 flex items-end justify-between gap-8"><div><p className="font-mono text-[9px] tracking-[.25em] text-cyan-300">01 / SYSTEMS LEDGER</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Built systems.<br /><span className="text-slate-500">Not slides.</span></h2></div><p className="hidden max-w-md text-right text-sm leading-6 text-slate-500 md:block">A public evidence layer for real prototypes, experiments and engineering work. Maturity is stated explicitly; representative interfaces are labelled as such.</p></div><div className="grid gap-2 lg:grid-cols-[.75fr_1.25fr]"><div className="border border-white/10 bg-white/[.02]">{systems.map((item, i) => <button key={item.id} onClick={() => setActive(i)} className={`w-full border-b border-white/10 p-5 text-left transition ${i === active ? 'bg-cyan-300/[.06]' : 'hover:bg-white/[.03]'}`}><div className="flex items-center gap-4"><span className="font-mono text-[9px] text-slate-600">{item.id}</span><span className="flex-1 font-mono text-xs tracking-[.16em]">{item.name}</span><span className="text-cyan-300">↗</span></div><p className="mt-2 pl-8 font-mono text-[8px] tracking-[.16em] text-slate-600">{item.type}</p></button>)}</div><div className="min-h-[430px] border border-white/10 bg-gradient-to-br from-white/[.04] to-cyan-300/[.025] p-7 lg:p-10"><div className="flex items-center justify-between"><span className="font-mono text-[9px] tracking-[.2em] text-cyan-300">SYSTEM {system.id}</span><span className="rounded-full border border-emerald-300/20 px-3 py-1 font-mono text-[8px] tracking-[.12em] text-emerald-200">{system.status}</span></div><h3 className="mt-20 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{system.name}</h3><p className="mt-5 max-w-2xl text-base leading-7 text-slate-400">{system.copy}</p><div className="mt-9 flex flex-wrap gap-2">{system.tags.map(tag => <span key={tag} className="border border-white/10 px-3 py-2 font-mono text-[8px] tracking-[.12em] text-slate-400">{tag}</span>)}</div><div className="mt-12 grid grid-cols-3 gap-2 border-t border-white/10 pt-5 font-mono text-[8px] text-slate-600"><span>STATE<br /><b className="text-slate-300">DOCUMENTED</b></span><span>MODE<br /><b className="text-slate-300">EDGE / HYBRID</b></span><span>PROOF<br /><b className="text-slate-300">REPOSITORY</b></span></div></div></div></section>
      <section id="capabilities" className="border-y border-white/10 bg-white/[.015]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="font-mono text-[9px] tracking-[.25em] text-cyan-300">02 / CAPABILITIES</p><div className="mt-10 grid gap-px overflow-hidden border border-white/10 bg-white/10 md:grid-cols-2">{capabilities.map(([title, copy], i) => <div key={title} className="bg-[#07090b] p-8"><span className="font-mono text-[9px] text-slate-600">0{i + 1}</span><h3 className="mt-8 text-2xl font-medium">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-slate-500">{copy}</p></div>)}</div></div></section>
      <section id="architecture" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="font-mono text-[9px] tracking-[.25em] text-cyan-300">03 / REFERENCE ARCHITECTURE</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Cloud when it helps.<br /><span className="text-slate-500">Edge when it matters.</span></h2><div className="mt-14 overflow-hidden border border-white/10 bg-black/30 p-5 font-mono text-[10px] sm:p-8"><div className="grid gap-3 md:grid-cols-5">{['PHYSICAL WORLD', 'EDGE COMPUTE', 'ORCHESTRATION', 'CLOUD SERVICES', 'INTELLIGENCE'].map((x, i) => <div key={x} className="border border-white/10 p-5"><span className="text-slate-600">0{i + 1}</span><strong className="mt-7 block text-slate-200">{x}</strong><p className="mt-3 text-[8px] leading-5 text-slate-600">{['Sensors · cameras · haptics · buses','Jetson · Pi · MCU · local models','MQTT · APIs · agents · memory','AWS · storage · telemetry · APIs','Models · perception · reasoning · action'][i]}</p></div>)}</div><div className="mt-6 border-t border-dashed border-cyan-300/20 pt-5 text-center text-[9px] tracking-[.18em] text-cyan-300">THE SYSTEM IS THE PRODUCT</div></div></section>
      <section id="about" className="border-t border-white/10"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[1fr_.8fr] lg:px-8"><div><p className="font-mono text-[9px] tracking-[.25em] text-cyan-300">04 / THE LAB</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">One builder.<br /><span className="text-slate-500">Full stack.</span></h2><p className="mt-7 max-w-2xl text-base leading-8 text-slate-400">NULLVECTOR LABS is a founder-led applied technology practice. The work moves across software, hardware, AI models, embedded Linux, mobile applications and physical interfaces — with the same rule throughout: make the claim smaller than the proof.</p></div><div className="border border-white/10 p-7 font-mono text-[9px] leading-7 text-slate-500"><p>LOCATION // AUSTRALIA</p><p>MODEL // INDEPENDENT R&D</p><p>FOCUS // EDGE + PHYSICAL AI</p><p>STACK // OPEN / CLOUD / LOCAL</p><p>STATUS // ACTIVE</p><div className="mt-7 border-t border-white/10 pt-5 text-cyan-200">BUILD → MEASURE → HARDEN → DEPLOY</div></div></div></section>
      <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 font-mono text-[8px] tracking-[.14em] text-slate-600 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© 2026 NULLVECTOR LABS</span><span>EDGE INTELLIGENCE · PHYSICAL AI · SYSTEMS ENGINEERING</span><a href="https://github.com/thotsl4yer69/mz1312" className="text-slate-400 hover:text-cyan-200">SOURCE / GITHUB ↗</a></div></footer>
    </main>
  );
}
